export default {
    appKey: "vtexappkey-garmin-HGCYIT",
    appToken: "IBGTVYUUOLTLQCOUXAPYBUDSRDALCPEGGUDJALBSPRUGTOMMPSSRSUJOYNCRXIRYHNEWYFTMYWIKAXZDROWKXMNMLPKMJKVHZVYFJPNKYFTVLYNBOYZJLHBUZSKJUHCO"
}